trigger:
  - master
  - feature/trigger-poc

pool:
  vmImage: "windows-latest"

parameters:
  - name: callerPL
    displayName: "Run stage 4"
    type: boolean
    default: false

stages:
  - stage: first
    variables:
      - group: perf_variables
    jobs:
      - job: Building_Policies
        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                # Write your commands here
                echo 'Hello world'
                echo $(check)

  - stage: second
    dependsOn: first
    # variables:
    #     - group: perf_variables
    jobs:
      - job: Building_Policies

        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                # Write your commands here
                echo 'Hello world'
                echo $(check)

  - stage: third
    dependsOn: first
    condition: eq('${{ parameters.callerPL }}', 'true')
    # variables:
    #     - group: perf_variables
    jobs:
      - job: Building_Policies

        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                # Write your commands here
                echo 'Hello world'
  - stage: fourth
    dependsOn:
      - third
      - second
    variables:
      - group: perf_variables
    jobs:
      - job: Building_Policies
        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                # Write your commands here
                echo 'Hello world 3'
                echo $(check)
