trigger:
  - master

pool:
  vmImage: "windows-latest"

parameters:
    - name: name
      displayName: Tell me your name.
      type: string
    
stages:
  - stage:
    # variables:
    #     - group: perf_variables
    jobs:
      - job: Building_Policies
        
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                echo 'Hello world'

      - job: seeing_Policies
        
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                echo 'seeing policies ' $(name)          
          # - task: PowerShell@2
          #   inputs:
          #     targetType: "inline"
          #     script: |
          #       # Echo out the Variables for the log      
          #       write-host $(environment)
          #       write-host $(B2CTENANTNAME) $(CLIENTCREDAPPID) $(ProxyIdentityExperienceFrameworkAppName) $(IdentityExperienceFrameworkAppName) $(B2CExtensionAttributeAppName) $(AppInsightInstrumentationKey) 
          #       # run the deployment script that modifies the policies and then uploads them
          #       .\scripts\build-prepare.ps1 -PolicyPath .\policies -PolicyPrefix $(B2CPolicyPrefix) -TenantName $(B2CTENANTNAME) -AppID $(CLIENTCREDAPPID) -AppKey $(CLIENTCREDAPPKEY) -ConfigKeyValues $params 
          # - task: CopyFiles@2
          #   inputs:
          #     SourceFolder: "$(System.DefaultWorkingDirectory)/policies"
          #     Contents: "**"
          #     TargetFolder: "$(Build.ArtifactStagingDirectory)/policies"
          #     CleanTargetFolder: true
          #     OverWrite: true

          # - task: CopyFiles@2
          #   inputs:
          #     SourceFolder: "$(System.DefaultWorkingDirectory)/scripts"
          #     Contents: "**"
          #     TargetFolder: "$(Build.ArtifactStagingDirectory)/scripts"
          #     CleanTargetFolder: true
          #     OverWrite: true

          # - task: PublishBuildArtifacts@1
          #   inputs:
          #     PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          #     ArtifactName: "drop"
          #     publishLocation: "Container"      