trigger:
  - master
  - poc-cms
# hi
# schedules:
#   - cron: "0 */24 */3 * Mon-Fri"
#     displayName: Daily midnight build
#     branches:
#       include:
#       - master
# - features/*
# exclude:
# - releases/ancient/*
pool:
  vmImage: "windows-latest"

stages:
  - stage:
    # variables:
    #   - group: asda-amplience-dev-vg
    #   - group: asda-amplience-qa-vg

    jobs:
      - job: Building_Scripts
        steps:
          - checkout: self
          - task: NodeTool@0
            inputs:
              versionSpec: 16.x
            displayName: "Install Node.js"
            condition: succeeded()

          - script: |
              npm install -g @amplience/dc-cli
            displayName: "npm install"

          # - task: PowerShell@2
          #   inputs:
          #     targetType: "inline"
          #     script: |
          #       dc-cli configure --clientId fb5c373c-73c4-406b-9d1e-2c25dff72870 --clientSecret 37bf959995f350ece653151fb4b77e6e4507b10b5507e821ef8d7adf7b60cb99 --hubId 624d8849c9e77c0001fe136a
          #       # dc-cli content-item export exportContentItems --facet "lastModifiedDate:Last 7 days"
          #       ls
          #       # cd / -recurse | Where-Object {$_.PSIsContainer -eq $true -and $_.Name -match ".amplience"}
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                # Write your commands here
                dc-cli configure --clientId fb5 --clientSecret 37bf959995f350ece653151fb4b77e6e4507b10b5507e821ef8d7adf7b60cb99 --hubId 624d8849c9e77c0001fe136a
                echo 'Hello world'
                find $HOME -type d -name ".amplience"
                cd / 
                cd /c/Users/VssAdministrator/.amplience
                ls -l
                cat dc-cli-config.json
                pwd
                mv D:/a/1/s/dc-cli-config.json /c/Users/VssAdministrator/.amplience
                mv D:/a/1/s/imports /c/Users/VssAdministrator/.amplience
                cat dc-cli-config.json
                ls -l
                dc-cli configure --clientId fb592497929 --clientSecret 37bf959995f350ece653151fb4b77e6e4507b10b5507e821ef8d7adf7b60cb99 --hubId 624d8849c9e77c0001fe136a
                mv /c/Users/VssAdministrator/.amplience/dc-cli-config.json D:/a/1/s
                
                # nano dc-cli-config.json
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                pwd
                git pull
                # git branch -a
                # echo 'Hello world'
                git checkout poc-cms
                git config --global user.email "yvnsraviteja1729@gmail.com"
                git config --global user.name "ravi teja"
                git add .
                git commit -m "updated json file"
                git status
                # git switch -c poc-cms1
                # git push origin poc-cms
                git push https://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@github.com/yvnsraviteja1729/adb2c.git
                # git push origin https://yvnsraviteja1729:$(System.AccessToken)@github.com/yvnsraviteja1729/adb2c.git 

