trigger:
  - master
  - poc-cms
# hi
# schedules:
#   - cron: "0 */24 */3 * Mon-Fri"
#     displayName: Daily midnight build
#     branches:
#       include:
#       - master
# - features/*
# exclude:
# - releases/ancient/*
pool:
  vmImage: "windows-latest"

stages:
  - stage:
    # variables:
    #   - group: asda-amplience-dev-vg
    #   - group: asda-amplience-qa-vg

    jobs:
      - job: Building_Scripts
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 16.x
            displayName: "Install Node.js"
            condition: succeeded()

          - script: |
              npm install -g @amplience/dc-cli
            displayName: "npm install"

          - task: PowerShell@2
            inputs:
              targetType: "inline"
              script: |
                dc-cli configure --clientId fb5c373c-73c4-406b-9d1e-2c25dff72870 --clientSecret 37bf959995f350ece653151fb4b77e6e4507b10b5507e821ef8d7adf7b60cb99 --hubId 624d8849c9e77c0001fe136a
                # dc-cli content-item export exportContentItems --facet "lastModifiedDate:Last 7 days"
                ls
                # cd / -recurse | Where-Object {$_.PSIsContainer -eq $true -and $_.Name -match ".amplience"}
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                # Write your commands here

                echo 'Hello world'
                find $HOME -type d -name ".amplience"
                cd / 
                cd /c/Users/VssAdministrator/.amplience
                ls
                # nano dc-cli-config.json
                mv D:/a/1/s/dc-cli-config.json /c/Users/VssAdministrator/.amplience
                ls
                # nano dc-cli-config.json
