trigger:
  - master
# hi
# schedules:
#   - cron: "0 */24 */3 * Mon-Fri"
#     displayName: Daily midnight build
#     branches:
#       include:
#       - master
# - features/*
# exclude:
# - releases/ancient/*
pool:
  vmImage: "windows-latest"

parameters:
  - name: callerPL
    displayName: "Run stage 4"
    type: boolean
    default: false


stages:
  - stage: first
    variables:
      - group: perf_variables
    jobs:
      # - job: Building_Policies

      #   steps:
      #     - task: Bash@3
      #       inputs:
      #         targetType: 'inline'
      #         script: |
      #           # Write your commands here
      #           echo 'Hello world'
      #           echo $(environment)

      - job: seeing_Policies
        steps:
          - template: template.yml
            parameters:
              whichState:
                - "Shop_Browse"
                - "Shop_CMS"
                - "Shop_BAC"
                - "Shop_Personalization"
                - "Manual_Execution"

        # steps:
        #   - task: Bash@3
        #     inputs:
        #       targetType: 'inline'
        #       script: |
        #         # Write your commands here
        #         echo 'seeing policies '

  - stage: second
    dependsOn: first
    # variables:
    #     - group: perf_variables
    jobs:
      - job: Building_Policies

        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                # Write your commands here
                echo 'Hello world'

      - job: seeing_Policies

        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                # Write your commands here
                echo "name         "
  - stage: third
    dependsOn: first
    condition: eq('${{ parameters.callerPL }}', 'true')
    # variables:
    #     - group: perf_variables
    jobs:
      - job: Building_Policies

        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                # Write your commands here
                echo 'Hello world'
  - stage: fourth
    dependsOn:
      - third
      - second
    variables:
      - group: perf_variables
    jobs:
      - job: Building_Policies
        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                # Write your commands here
                echo 'Hello world 3'
                echo $(environment)

      - job: seeing_Policies

        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                # Write your commands here
                echo 'seeing policies 3'
      - deployment: DeployWeb
        condition: succeeded()
        dependsOn: 
          - Building_Policies
          - seeing_Policies
        displayName: deploy Web App
        pool:
          vmImage: 'Ubuntu-latest'
        # creates an environment if it doesn't exist
        environment: 'manual_approval'
        strategy:
          runOnce:
            deploy:
              steps:
              - script: echo Hello world
      